### ISSUE TITLE
build warnings in wdi-simple.c

### ISSUE THREAD

**Issue by prusnak** [trezor/trezord-go#118]
```
wdi-simple.c: In function 'main':
wdi-simple.c:93:40: warning: variable 'ocl' set but not used [-Wunused-but-set-variable]
  static struct wdi_options_create_list ocl = { 0 };
                                        ^~~
wdi-simple.c:92:33: warning: unused variable 'ldev' [-Wunused-variable]
  static struct wdi_device_info *ldev, dev = {NULL, VID, PID, FALSE, 0, DESC, NULL, NULL, NULL};
                                 ^~~~
At top level:
wdi-simple.c:92:33: warning: 'ldev' defined but not used [-Wunused-variable]
```

let's just remove `ocl` and `ldev` variables if they are not needed anymore

**Comment by karel-3d** [comment]
I didn't want to touch this code, since it's a black box to me more or less :) but why not I guess

**Comment by prusnak** [comment]
I thought it was already heavily modified by you ... If this warnings were not caused by your modifications then I am happy with WONTFIX

**Comment by karel-3d** [comment]
I am not sure, but I think it isn't. I can try

**Comment by karel-3d** [comment]
Oh it actually is my modification.

Originally, the wdi-simple decides - if it sees connected device with the
vid/pid, it installs driver JUST for that device and does some other magic
around it.

Because we have a device detection in the NSIS installer, we never run the
wdi-simple when the device is connected, so I removed the detection, since
it actually caused some problem on one computer.

So yeah I will fix it
