### ISSUE TITLE
Make trezord-go usable as a library (and write docs for that)

### ISSUE THREAD

**Issue by karelbilek** [trezor/trezord-go#143]
Trezord-go might be usable as a library for other programs, but it would need some more thinking and documentation.

**Comment by karel-3d** [comment]
One point, when toying with the writing of this as a library:

Here, we do not do protobuf encoding. So, all messages go in/out as bytes; because we wanted to have the encoding/decoding in JavaScript.

However, if we want to allow go apps to use this as library, it would probably be good to add the protobuf encoding/decoding?

The problem is, golang doesn't have "dynamic" protobuf encoding in the official Google's protobuf repo. It needs to auto-generate go code from protobuf definitions. We can do that; but it will be a little annoying to update that all the time.

Or, there is a dynamic protobuf encoding/decoding for go, but then the messages will not be typechecked.

I am not sure what is better.
