### ISSUE TITLE
macOS uninstaller doesn't work on Catalina

### ISSUE THREAD

**Issue by karelbilek** [trezor/trezord-go#186]
Uninstaller doesn't work on Catalina anymore.

**Comment by sorooris** [comment]
Might be associated with this issue and #194 

**Describe the bug**
Uninstalling the Bridge 2.0.30 RC3 ends in an error; however the uninstall process is **finished** after restart (no trezord process running and the [URL + port](http://127.0.0.1:21325/status/#) can not be reached).

**App version and revision**
Bridge 2.0.30 RC3 (8a597a)

**Setup:**
 - OS: MacOS Catalina 10.15.6

**Steps to reproduce:**
1. Start the uninstall wizard,
2. Navigate through the steps,
3. See error.

**Expected behavior**
_Uninstall_ wizard is displayed and ends successfully.

**Screenshots**
N/A

**Additional context**
Bridge can be uninstalled by deleting the contaning folder in Utilities and restarting the machine.

**Comment by prusnak** [comment]
Fixed in 80a5abfe7c6dc3ad327389c77daa6e71bcebe88b
