### ISSUE TITLE
Expand README with information why Trezor Bridge exists

### ISSUE THREAD

**Issue by kucharskim** [trezor/trezord-go#218]
- Why Trezor Bridge exists
- What is it's purpose
- What does it do
- When it's needed (in what technical situation there would be a need for it, for example what operating system, what web browser, what OS setup makes Trezor Bridge mandatory or needed)

I find documentation about Trezor Bridge very terse.

**Comment by prusnak** [comment]
1. Because Firefox and other browsers do not support WebUSB (as opposed to Chrome which supports it).
2. We need to offer a way how a website such as wallet.trezor.io can communicate with the USB device such as Trezor.
3. It scans USB for devices that match Trezor devices VendorIDs/ProductIDs and exposes a HTTP server running on localhost that provides a way how to communicate with these devices via REST API.
4. It's needed for any OS, any browser except Chrome (which supports connecting to USB devices via WebUSB).

**Comment by kucharskim** [comment]
Ok, I've looked at OpenBSD chromium port and as of today (January 2021, chromium-88.0.4324.96) WebUSB is disabled on OpenBSD. In other words, having Chrome web browser doesn't guarantee that WebUSB works.

Your above clarification is very helpful. Thanks.

**Comment by Puskas198103** [comment]
Hello mit kel most tennem

**Comment by igor-hnizdo** [comment]
Just a note - it also helps with old devices (pre-2018-ish) that still run on HID.

In order to migrate them to WebUSB.

**Comment by igor-hnizdo** [comment]
I wrote something in this PR #279

**Comment by tsusanka** [comment]
Merged in https://github.com/trezor/trezord-go/commit/39d21970aae9f130b42c496f12fe11a6dfe5b7ae.
