### ISSUE TITLE
trezord.exe listens on 16000+ ports

### ISSUE THREAD

**Issue by baremetalfreak** [trezor/trezord-go#93]
[netstat.txt](https://github.com/trezor/trezord-go/files/2370200/netstat.txt)

Let me know what else you need to diagnose this.

**Comment by karel-3d** [comment]
That's super weird, since 21325 port is not actually even open in the netstat.... what is going on?

What version of trezord do you have installed? Maybe you have the old version in C++? What do you see, if anything, on http://127.0.0.1:21325/ , as a version?

If you have 2.* version - is web wallet actually working for you? What do you see as a first line after clicking at "show log" in the footer at web wallet?

**Comment by karel-3d** [comment]
I have already found that it's actually issue with Trezor Bridge v1 and not this one. So it is already fixed.

Please install new bridge. You can find it at https://wallet.trezor.io/#/bridge

**Comment by baremetalfreak** [comment]
Ok so  http://127.0.0.1:21325/ was not available. Installing new version of bridge seems to have solved the problem.  http://127.0.0.1:21325/ is now available and trezord.exe has only one port open
```
[trezord.exe]
 TCP    127.0.0.1:44430        Reason:0               LISTENING
```

Thank you!

**Comment by karel-3d** [comment]
(because I am curious to my detriment, I tried to find out the actual bug in old trezord v1. But it seems to be a bug in mingw - the issue is not reproducible if I build *old* trezord anew, but it is reproducible with the latest binary. So it is probably some mingw issue that already got fixed upstream. Anyway trezord v1 is not supported.)
